-- Enable pgcrypto for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO "Course" ("id", "title", "description", "price", "duration", "imageUrl", "published", "createdAt", "updatedAt") VALUES
(gen_random_uuid()::text, 'Auxiliar de creche', 'Curso completo de Auxiliar de creche com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'AVE-Auxiliar de vida escolar', 'Curso completo de AVE-Auxiliar de vida escolar com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Educação Especial', 'Curso completo de Educação Especial com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'AEE', 'Curso completo de AEE com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Auxiliar Administrativo', 'Curso completo de Auxiliar Administrativo com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Recursos Humanos', 'Curso completo de Recursos Humanos com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Informática Administrativa', 'Curso completo de Informática Administrativa com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Logística', 'Curso completo de Logística com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Segurança do trabalho', 'Curso completo de Segurança do trabalho com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Agente de Portaria e Vigia Escolar', 'Curso completo de Agente de Portaria e Vigia Escolar com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Inteligência Emocional', 'Curso completo de Inteligência Emocional com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Agente de Saúde', 'Curso completo de Agente de Saúde com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Agente de combate as endemias', 'Curso completo de Agente de combate as endemias com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Auxiliar Jurídico', 'Curso completo de Auxiliar Jurídico com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Operador de Caixa', 'Curso completo de Operador de Caixa com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Recepcionista e Atendimento ao Cliente', 'Curso completo de Recepcionista e Atendimento ao Cliente com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Liderança', 'Curso completo de Liderança com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Negócios do Zero', 'Curso completo de Negócios do Zero com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Empregabilidade', 'Curso completo de Empregabilidade com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Oratória e Comunicação', 'Curso completo de Oratória e Comunicação com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Desenvolvimento Pessoal', 'Curso completo de Desenvolvimento Pessoal com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Vendas', 'Curso completo de Vendas com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Inglês Básico', 'Curso completo de Inglês Básico com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Inglês Intermediário', 'Curso completo de Inglês Intermediário com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Inglês Avançado', 'Curso completo de Inglês Avançado com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Operador de computador', 'Curso completo de Operador de computador com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Cuidador de idosos', 'Curso completo de Cuidador de idosos com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Noções de elétrica Básica', 'Curso completo de Noções de elétrica Básica com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Estética Básica e limpeza de pele', 'Curso completo de Estética Básica e limpeza de pele com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Maquiagem Básica', 'Curso completo de Maquiagem Básica com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Designer de Sobrancelhas', 'Curso completo de Designer de Sobrancelhas com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Extensão de cilios', 'Curso completo de Extensão de cilios com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Massagem', 'Curso completo de Massagem com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Depilação', 'Curso completo de Depilação com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Manutenção de celular', 'Curso completo de Manutenção de celular com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Barbeiro', 'Curso completo de Barbeiro com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Alfabetização', 'Curso completo de Alfabetização com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Libras', 'Curso completo de Libras com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Secretariado', 'Curso completo de Secretariado com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Primeiros socorros', 'Curso completo de Primeiros socorros com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Aplicação de Injetáveis', 'Curso completo de Aplicação de Injetáveis com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Balconista de Farmácia', 'Curso completo de Balconista de Farmácia com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Farmacologia', 'Curso completo de Farmacologia com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Vendedor', 'Curso completo de Vendedor com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Padeiro', 'Curso completo de Padeiro com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Marketing Digital', 'Curso completo de Marketing Digital com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Vendas Onlines', 'Curso completo de Vendas Onlines com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Manutenção de Notebook', 'Curso completo de Manutenção de Notebook com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Manutenção de Impressoras', 'Curso completo de Manutenção de Impressoras com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Rede de computadores', 'Curso completo de Rede de computadores com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Provas para o ENEM', 'Curso completo de Provas para o ENEM com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Estoquista', 'Curso completo de Estoquista com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Auxiliar Bucal', 'Curso completo de Auxiliar Bucal com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Manicure e Pedicure', 'Curso completo de Manicure e Pedicure com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Doces e Salgados', 'Curso completo de Doces e Salgados com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Furo Humanizado', 'Curso completo de Furo Humanizado com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Excel', 'Curso completo de Excel com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Word', 'Curso completo de Word com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Power Point', 'Curso completo de Power Point com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Internet', 'Curso completo de Internet com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Windows', 'Curso completo de Windows com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Como gravar videos e editar no CapCut', 'Curso completo de Como gravar videos e editar no CapCut com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Canva', 'Curso completo de Canva com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Corel Draw', 'Curso completo de Corel Draw com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Foto Shop', 'Curso completo de Foto Shop com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Veterinário', 'Curso completo de Veterinário com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Redação', 'Curso completo de Redação com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Matemática', 'Curso completo de Matemática com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Português', 'Curso completo de Português com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Administração', 'Curso completo de Administração com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Psicologia Básica', 'Curso completo de Psicologia Básica com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Introdução a Pedagogia', 'Curso completo de Introdução a Pedagogia com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Educação infantil', 'Curso completo de Educação infantil com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Ludicidade', 'Curso completo de Ludicidade com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Ludopedagogia', 'Curso completo de Ludopedagogia com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Psicopedagogia', 'Curso completo de Psicopedagogia com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Neurociência', 'Curso completo de Neurociência com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Informática aplicada a educação', 'Curso completo de Informática aplicada a educação com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Metodologias ativas de aprendizagem', 'Curso completo de Metodologias ativas de aprendizagem com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Empreendedorismo', 'Curso completo de Empreendedorismo com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Marketing', 'Curso completo de Marketing com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Introdução ao serviço social', 'Curso completo de Introdução ao serviço social com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Enfermagem básica', 'Curso completo de Enfermagem básica com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Saúde da Mulher', 'Curso completo de Saúde da Mulher com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Recepcionista de UBS', 'Curso completo de Recepcionista de UBS com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'Noções de Triagem', 'Curso completo de Noções de Triagem com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'APH Atendimento pré hospitalar', 'Curso completo de APH Atendimento pré hospitalar com certificação profissional.', 99.90, 40, NULL, true, NOW(), NOW());
